version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: usuario_viva
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mercado_viva
    ports:
      - "5432:5432"
