version: "3.9"
services:
  db:
    image: postgres:16
    container_name: mercado-viva-db
    environment:
      POSTGRES_USER: mercado_user
      POSTGRES_PASSWORD: mercado_pass
      POSTGRES_DB: mercado_viva
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: mercado-viva-backend
    environment:
      DATABASE_URL: postgresql://mercado_user:mercado_pass@db:5432/mercado_viva
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - db
    # Usamos el script "dev" que utiliza nodemon para recargar los cambios en vivo
    command: npm run dev

volumes:
  db_data: